// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    IconAtom: typeof import('./src/components/ui/icons/icon-atom.vue')['default']
    IconEdit: typeof import('./src/components/ui/icons/icon-edit.vue')['default']
    IconEyeClosed: typeof import('./src/components/ui/icons/icon-eye-closed.vue')['default']
    IconEyeOpened: typeof import('./src/components/ui/icons/icon-eye-opened.vue')['default']
    IconLightning: typeof import('./src/components/ui/icons/icon-lightning.vue')['default']
    IconLock: typeof import('./src/components/ui/icons/icon-lock.vue')['default']
    IconLogin: typeof import('./src/components/ui/icons/icon-login.vue')['default']
    IconLogout: typeof import('./src/components/ui/icons/icon-logout.vue')['default']
    IconUnlock: typeof import('./src/components/ui/icons/icon-unlock.vue')['default']
    IconUser: typeof import('./src/components/ui/icons/icon-user.vue')['default']
    IconUsers: typeof import('./src/components/ui/icons/icon-users.vue')['default']
    IconWarning: typeof import('./src/components/ui/icons/icon-warning.vue')['default']
    LdCheckbox: typeof import('./src/components/fields/ld-checkbox.vue')['default']
    LdInput: typeof import('./src/components/fields/ld-input.vue')['default']
    LdNavbar: typeof import('./src/components/ui/ld-navbar.vue')['default']
    LdPassword: typeof import('./src/components/fields/ld-password.vue')['default']
    LdRadiobutton: typeof import('./src/components/fields/ld-radiobutton.vue')['default']
    LdSidebar: typeof import('./src/components/ui/ld-sidebar.vue')['default']
    LdTextarea: typeof import('./src/components/fields/ld-textarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserEdit: typeof import('./src/components/user-edit.vue')['default']
  }
}
